# common
model_name: hpnet
num_modes: 6
hidden_dim: 128
num_historical_steps: 20
num_future_steps: 30
pos_duration: 20
pred_duration: 20
a2a_radius: 50
l2a_radius: 50
num_visible_steps: 2
num_attn_layers: 2
num_hops: 4
num_heads: 8
dropout: 0.1

# train
max_epochs: 100 
warmup_epochs: 4
learning_rate: 0.0003
weight_decay: 0.0001
learning_rate_sched: [10, 20, 30, 40, 50]
T_max: 64
optimizer: Adam 
scheduler: multistep 
ewc_lambda: 2000
train_batch_size: 128 
eval_batch_size: 256 
grad_clip_norm: 5

# data related
max_num_agents: 15
map_range: 100
max_num_roads: 256
max_points_per_lane: 20 
manually_split_lane: False
point_sampled_interval: 1
num_points_each_polyline: 20
vector_break_dist_thresh: 1.0



